# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a6d95cb57d3b27e9792a264a981a46dbbba975ad214ea2f15b9d8a769fe62a01096a39a5e705e2709c543719a4e682081b048f0596bf9af5aa451359b71643c

test:
  secret_key_base: 1f8ae11102af0ae9928288da10c2bc83ca8f29a05a5f3a262c1824a75e250bd01c8e0bb9c8a67ae04bb8d894dd0d1b2290776e8806df3dc232b17c4e2d7718d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
